resilience4j.circuitbreaker:
    instances:
        usersService: #can be any name
          failure-rate-threshold: 50
          ring-buffer-size-in-closed-state: 5
          ring-buffer-size-in-half-open-state: 3
          wait-duration-in-open-state: 30s #time until we retry opening the circuit
          automatic-transition-from-open-to-half-open-enabled: true